// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxuv_uGfGFS-Lg3qEeBjq3gNHAHNo_RJg',
    appId: '1:704085484303:web:81eb0e0a85c30b8c4f147a',
    messagingSenderId: '704085484303',
    projectId: 'flutter-proyek-6dd7f',
    authDomain: 'flutter-proyek-6dd7f.firebaseapp.com',
    storageBucket: 'flutter-proyek-6dd7f.firebasestorage.app',
    measurementId: 'G-47XB9BSSXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2-tapDgclA3IvgSS_ofts-v4c9z54wx4',
    appId: '1:704085484303:android:9fcb0162b047ad884f147a',
    messagingSenderId: '704085484303',
    projectId: 'flutter-proyek-6dd7f',
    storageBucket: 'flutter-proyek-6dd7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSufTM1kJjLdINxuKrRajq7PFmzg1Yegg',
    appId: '1:704085484303:ios:c0bdd28322d277214f147a',
    messagingSenderId: '704085484303',
    projectId: 'flutter-proyek-6dd7f',
    storageBucket: 'flutter-proyek-6dd7f.firebasestorage.app',
    iosBundleId: 'com.example.flutterProyekKel02',
  );

}